# CMake generated Testfile for 
# Source directory: C:/VSC_Project/ConvoPeq
# Build directory: C:/VSC_Project/ConvoPeq/build-t1-test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("PublicationAdmissionTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/PublicationAdmissionTests.exe")
  set_tests_properties("PublicationAdmissionTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;176;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("PublicationAdmissionTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/PublicationAdmissionTests.exe")
  set_tests_properties("PublicationAdmissionTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;176;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("PublicationAdmissionTests" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/PublicationAdmissionTests.exe")
  set_tests_properties("PublicationAdmissionTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;176;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("PublicationAdmissionTests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("TerminalTelemetryContract" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/TerminalTelemetryContractTests.exe")
  set_tests_properties("TerminalTelemetryContract" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;267;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("TerminalTelemetryContract" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/TerminalTelemetryContractTests.exe")
  set_tests_properties("TerminalTelemetryContract" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;267;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("TerminalTelemetryContract" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/TerminalTelemetryContractTests.exe")
  set_tests_properties("TerminalTelemetryContract" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;267;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("TerminalTelemetryContract" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("ISRSoakTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/ISRSoakTests.exe")
  set_tests_properties("ISRSoakTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;333;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("ISRSoakTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/ISRSoakTests.exe")
  set_tests_properties("ISRSoakTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;333;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("ISRSoakTests" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/ISRSoakTests.exe")
  set_tests_properties("ISRSoakTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;333;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("ISRSoakTests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("OwnerChannel" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/OwnerChannelTests.exe")
  set_tests_properties("OwnerChannel" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;348;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("OwnerChannel" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/OwnerChannelTests.exe")
  set_tests_properties("OwnerChannel" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;348;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("OwnerChannel" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/OwnerChannelTests.exe")
  set_tests_properties("OwnerChannel" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;348;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("OwnerChannel" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("DeferredDeletionQueueReclaimTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/DeferredDeletionQueueReclaimTests.exe")
  set_tests_properties("DeferredDeletionQueueReclaimTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;400;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("DeferredDeletionQueueReclaimTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/DeferredDeletionQueueReclaimTests.exe")
  set_tests_properties("DeferredDeletionQueueReclaimTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;400;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("DeferredDeletionQueueReclaimTests" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/DeferredDeletionQueueReclaimTests.exe")
  set_tests_properties("DeferredDeletionQueueReclaimTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;400;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("DeferredDeletionQueueReclaimTests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("MpscBoundedRingTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/MpscBoundedRingTests.exe")
  set_tests_properties("MpscBoundedRingTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;411;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("MpscBoundedRingTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/MpscBoundedRingTests.exe")
  set_tests_properties("MpscBoundedRingTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;411;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("MpscBoundedRingTests" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/MpscBoundedRingTests.exe")
  set_tests_properties("MpscBoundedRingTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;411;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("MpscBoundedRingTests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("SequenceArithmeticTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/SequenceArithmeticTests.exe")
  set_tests_properties("SequenceArithmeticTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;419;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("SequenceArithmeticTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/SequenceArithmeticTests.exe")
  set_tests_properties("SequenceArithmeticTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;419;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("SequenceArithmeticTests" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/SequenceArithmeticTests.exe")
  set_tests_properties("SequenceArithmeticTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;419;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("SequenceArithmeticTests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("DSPHandleTableTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/DSPHandleTableTests.exe")
  set_tests_properties("DSPHandleTableTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;427;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("DSPHandleTableTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/DSPHandleTableTests.exe")
  set_tests_properties("DSPHandleTableTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;427;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("DSPHandleTableTests" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/DSPHandleTableTests.exe")
  set_tests_properties("DSPHandleTableTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;427;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("DSPHandleTableTests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("GainStagingContractTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/GainStagingContractTests.exe")
  set_tests_properties("GainStagingContractTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;459;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("GainStagingContractTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/GainStagingContractTests.exe")
  set_tests_properties("GainStagingContractTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;459;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("GainStagingContractTests" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/GainStagingContractTests.exe")
  set_tests_properties("GainStagingContractTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;459;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("GainStagingContractTests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("EQProcessorMaxGainTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/EQProcessorMaxGainTests.exe")
  set_tests_properties("EQProcessorMaxGainTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;468;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("EQProcessorMaxGainTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/EQProcessorMaxGainTests.exe")
  set_tests_properties("EQProcessorMaxGainTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;468;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("EQProcessorMaxGainTests" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/EQProcessorMaxGainTests.exe")
  set_tests_properties("EQProcessorMaxGainTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;468;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("EQProcessorMaxGainTests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("EQAnalysisUnitTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/EQAnalysisUnitTests.exe")
  set_tests_properties("EQAnalysisUnitTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;477;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("EQAnalysisUnitTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/EQAnalysisUnitTests.exe")
  set_tests_properties("EQAnalysisUnitTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;477;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("EQAnalysisUnitTests" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/EQAnalysisUnitTests.exe")
  set_tests_properties("EQAnalysisUnitTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;477;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("EQAnalysisUnitTests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("FFTBackendTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/FFTBackendTests.exe")
  set_tests_properties("FFTBackendTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;493;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("FFTBackendTests" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/FFTBackendTests.exe")
  set_tests_properties("FFTBackendTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;493;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("FFTBackendTests" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/FFTBackendTests.exe")
  set_tests_properties("FFTBackendTests" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;493;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("FFTBackendTests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("EQBoundExcessBenchmark" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/EQBoundExcessBenchmark.exe" "--quick")
  set_tests_properties("EQBoundExcessBenchmark" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;501;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("EQBoundExcessBenchmark" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/EQBoundExcessBenchmark.exe" "--quick")
  set_tests_properties("EQBoundExcessBenchmark" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;501;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("EQBoundExcessBenchmark" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/EQBoundExcessBenchmark.exe" "--quick")
  set_tests_properties("EQBoundExcessBenchmark" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;501;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("EQBoundExcessBenchmark" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("ISRRuntimeIdentityGenerators" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/ISRRuntimeIdentityTests.exe")
  set_tests_properties("ISRRuntimeIdentityGenerators" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;691;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("ISRRuntimeIdentityGenerators" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/ISRRuntimeIdentityTests.exe")
  set_tests_properties("ISRRuntimeIdentityGenerators" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;691;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("ISRRuntimeIdentityGenerators" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/ISRRuntimeIdentityTests.exe")
  set_tests_properties("ISRRuntimeIdentityGenerators" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;691;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("ISRRuntimeIdentityGenerators" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("RuntimePublicationCoordinatorRejects" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/RuntimePublicationCoordinatorTests.exe")
  set_tests_properties("RuntimePublicationCoordinatorRejects" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;692;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("RuntimePublicationCoordinatorRejects" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/RuntimePublicationCoordinatorTests.exe")
  set_tests_properties("RuntimePublicationCoordinatorRejects" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;692;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("RuntimePublicationCoordinatorRejects" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/RuntimePublicationCoordinatorTests.exe")
  set_tests_properties("RuntimePublicationCoordinatorRejects" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;692;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("RuntimePublicationCoordinatorRejects" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("ISRSemanticValidationRejects" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/ISRSemanticValidationTests.exe")
  set_tests_properties("ISRSemanticValidationRejects" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;693;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("ISRSemanticValidationRejects" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/ISRSemanticValidationTests.exe")
  set_tests_properties("ISRSemanticValidationRejects" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;693;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("ISRSemanticValidationRejects" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/ISRSemanticValidationTests.exe")
  set_tests_properties("ISRSemanticValidationRejects" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;693;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("ISRSemanticValidationRejects" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("InvariantINV3INV5" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/invariant_INV3_INV5Tests.exe")
  set_tests_properties("InvariantINV3INV5" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;694;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("InvariantINV3INV5" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/invariant_INV3_INV5Tests.exe")
  set_tests_properties("InvariantINV3INV5" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;694;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("InvariantINV3INV5" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/invariant_INV3_INV5Tests.exe")
  set_tests_properties("InvariantINV3INV5" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;694;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("InvariantINV3INV5" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("RetireGraceSemantics" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/RetireGraceSemanticsTests.exe")
  set_tests_properties("RetireGraceSemantics" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;695;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("RetireGraceSemantics" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/RetireGraceSemanticsTests.exe")
  set_tests_properties("RetireGraceSemantics" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;695;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("RetireGraceSemantics" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/RetireGraceSemanticsTests.exe")
  set_tests_properties("RetireGraceSemantics" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;695;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("RetireGraceSemantics" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("ShutdownRetireIntentDrain" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/ShutdownRetireIntentDrainTests.exe")
  set_tests_properties("ShutdownRetireIntentDrain" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;696;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("ShutdownRetireIntentDrain" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/ShutdownRetireIntentDrainTests.exe")
  set_tests_properties("ShutdownRetireIntentDrain" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;696;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("ShutdownRetireIntentDrain" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/ShutdownRetireIntentDrainTests.exe")
  set_tests_properties("ShutdownRetireIntentDrain" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;696;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("ShutdownRetireIntentDrain" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("StuckReaderFallbackDrain" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/StuckReaderFallbackDrainTests.exe")
  set_tests_properties("StuckReaderFallbackDrain" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;697;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("StuckReaderFallbackDrain" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/StuckReaderFallbackDrainTests.exe")
  set_tests_properties("StuckReaderFallbackDrain" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;697;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("StuckReaderFallbackDrain" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/StuckReaderFallbackDrainTests.exe")
  set_tests_properties("StuckReaderFallbackDrain" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;697;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("StuckReaderFallbackDrain" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("NormalRetireDSPHandleCompare" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/NormalRetireDSPHandleCompareTests.exe")
  set_tests_properties("NormalRetireDSPHandleCompare" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;698;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("NormalRetireDSPHandleCompare" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/NormalRetireDSPHandleCompareTests.exe")
  set_tests_properties("NormalRetireDSPHandleCompare" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;698;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("NormalRetireDSPHandleCompare" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/NormalRetireDSPHandleCompareTests.exe")
  set_tests_properties("NormalRetireDSPHandleCompare" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;698;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("NormalRetireDSPHandleCompare" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("RuntimeSemanticSchemaValidation" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/RuntimeSemanticSchemaValidationTests.exe")
  set_tests_properties("RuntimeSemanticSchemaValidation" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;699;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("RuntimeSemanticSchemaValidation" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/RuntimeSemanticSchemaValidationTests.exe")
  set_tests_properties("RuntimeSemanticSchemaValidation" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;699;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("RuntimeSemanticSchemaValidation" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/RuntimeSemanticSchemaValidationTests.exe")
  set_tests_properties("RuntimeSemanticSchemaValidation" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;699;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("RuntimeSemanticSchemaValidation" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("ObservePathSingleSource" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/ObservePathSingleSourceTests.exe")
  set_tests_properties("ObservePathSingleSource" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;700;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("ObservePathSingleSource" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/ObservePathSingleSourceTests.exe")
  set_tests_properties("ObservePathSingleSource" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;700;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("ObservePathSingleSource" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/ObservePathSingleSourceTests.exe")
  set_tests_properties("ObservePathSingleSource" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;700;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("ObservePathSingleSource" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("OverlapAuthoritySingular" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/OverlapAuthoritySingularTests.exe")
  set_tests_properties("OverlapAuthoritySingular" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;701;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("OverlapAuthoritySingular" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/OverlapAuthoritySingularTests.exe")
  set_tests_properties("OverlapAuthoritySingular" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;701;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("OverlapAuthoritySingular" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/OverlapAuthoritySingularTests.exe")
  set_tests_properties("OverlapAuthoritySingular" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;701;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("OverlapAuthoritySingular" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("ShadowCompareContract" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/ShadowCompareContractTests.exe")
  set_tests_properties("ShadowCompareContract" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;702;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("ShadowCompareContract" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/ShadowCompareContractTests.exe")
  set_tests_properties("ShadowCompareContract" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;702;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("ShadowCompareContract" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/ShadowCompareContractTests.exe")
  set_tests_properties("ShadowCompareContract" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;702;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("ShadowCompareContract" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("CrossfadeExecutorLocalContract" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/CrossfadeExecutorLocalContractTests.exe")
  set_tests_properties("CrossfadeExecutorLocalContract" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;703;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("CrossfadeExecutorLocalContract" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/CrossfadeExecutorLocalContractTests.exe")
  set_tests_properties("CrossfadeExecutorLocalContract" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;703;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("CrossfadeExecutorLocalContract" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/CrossfadeExecutorLocalContractTests.exe")
  set_tests_properties("CrossfadeExecutorLocalContract" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;703;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("CrossfadeExecutorLocalContract" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("RuntimeWorldAuthorityProjectionContract" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/RuntimeWorldAuthorityProjectionTests.exe")
  set_tests_properties("RuntimeWorldAuthorityProjectionContract" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;704;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("RuntimeWorldAuthorityProjectionContract" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/RuntimeWorldAuthorityProjectionTests.exe")
  set_tests_properties("RuntimeWorldAuthorityProjectionContract" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;704;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("RuntimeWorldAuthorityProjectionContract" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/RuntimeWorldAuthorityProjectionTests.exe")
  set_tests_properties("RuntimeWorldAuthorityProjectionContract" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;704;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("RuntimeWorldAuthorityProjectionContract" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("PartialPublicationReject" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/PartialPublicationRejectTests.exe")
  set_tests_properties("PartialPublicationReject" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;705;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("PartialPublicationReject" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/PartialPublicationRejectTests.exe")
  set_tests_properties("PartialPublicationReject" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;705;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("PartialPublicationReject" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/PartialPublicationRejectTests.exe")
  set_tests_properties("PartialPublicationReject" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;705;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("PartialPublicationReject" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("RebuildAdmissionRegression" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/RebuildAdmissionRegressionTests.exe")
  set_tests_properties("RebuildAdmissionRegression" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;706;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("RebuildAdmissionRegression" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/RebuildAdmissionRegressionTests.exe")
  set_tests_properties("RebuildAdmissionRegression" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;706;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("RebuildAdmissionRegression" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/RebuildAdmissionRegressionTests.exe")
  set_tests_properties("RebuildAdmissionRegression" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;706;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("RebuildAdmissionRegression" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("HeadlessAudioPathVerification" "powershell" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "C:/VSC_Project/ConvoPeq/.github/scripts/cli-smoke-test.ps1" "-KillExisting" "-RequireAudioCallbacks")
  set_tests_properties("HeadlessAudioPathVerification" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;709;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("HeadlessAudioPathVerification" "powershell" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "C:/VSC_Project/ConvoPeq/.github/scripts/cli-smoke-test.ps1" "-KillExisting" "-RequireAudioCallbacks")
  set_tests_properties("HeadlessAudioPathVerification" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;709;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("HeadlessAudioPathVerification" "powershell" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "C:/VSC_Project/ConvoPeq/.github/scripts/cli-smoke-test.ps1" "-KillExisting" "-RequireAudioCallbacks")
  set_tests_properties("HeadlessAudioPathVerification" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;709;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("HeadlessAudioPathVerification" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("BuildInputSemanticContract" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/BuildInputSemanticContractTests.exe")
  set_tests_properties("BuildInputSemanticContract" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;711;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("BuildInputSemanticContract" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/BuildInputSemanticContractTests.exe")
  set_tests_properties("BuildInputSemanticContract" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;711;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("BuildInputSemanticContract" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/BuildInputSemanticContractTests.exe")
  set_tests_properties("BuildInputSemanticContract" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;711;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("BuildInputSemanticContract" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("PriorityIntegration" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/PriorityIntegrationTests.exe")
  set_tests_properties("PriorityIntegration" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;712;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("PriorityIntegration" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/PriorityIntegrationTests.exe")
  set_tests_properties("PriorityIntegration" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;712;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("PriorityIntegration" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/PriorityIntegrationTests.exe")
  set_tests_properties("PriorityIntegration" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;712;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("PriorityIntegration" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("MTNUPCMeasurement" "C:/VSC_Project/ConvoPeq/build-t1-test/MTNUPCMeasurement_artefacts/Debug/MTNUPCMeasurement.exe")
  set_tests_properties("MTNUPCMeasurement" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;962;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("MTNUPCMeasurement" "C:/VSC_Project/ConvoPeq/build-t1-test/MTNUPCMeasurement_artefacts/Release/MTNUPCMeasurement.exe")
  set_tests_properties("MTNUPCMeasurement" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;962;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("MTNUPCMeasurement" "C:/VSC_Project/ConvoPeq/build-t1-test/MTNUPCMeasurement_artefacts/RelWithDebInfo/MTNUPCMeasurement.exe")
  set_tests_properties("MTNUPCMeasurement" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;962;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("MTNUPCMeasurement" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("AudioEngineHarness" "C:/VSC_Project/ConvoPeq/build-t1-test/Debug/AudioEngineHarness.exe")
  set_tests_properties("AudioEngineHarness" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;1788;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("AudioEngineHarness" "C:/VSC_Project/ConvoPeq/build-t1-test/Release/AudioEngineHarness.exe")
  set_tests_properties("AudioEngineHarness" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;1788;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("AudioEngineHarness" "C:/VSC_Project/ConvoPeq/build-t1-test/RelWithDebInfo/AudioEngineHarness.exe")
  set_tests_properties("AudioEngineHarness" PROPERTIES  _BACKTRACE_TRIPLES "C:/VSC_Project/ConvoPeq/CMakeLists.txt;1788;add_test;C:/VSC_Project/ConvoPeq/CMakeLists.txt;0;")
else()
  add_test("AudioEngineHarness" NOT_AVAILABLE)
endif()
subdirs("JUCE")
