#!/usr/bin/env python3
"""
Real IR Download Helper for Auto Gain Staging Benchmarks.

OpenAIR (https://www.openair.hosted.york.ac.uk/) hosts a large collection of
acoustic impulse responses, but does not provide a programmatic download API.
Each IR is on its own WordPress post page with a WAV file attachment.

This script provides:
1. A list of recommended IRs for download (organized by category)
2. Instructions for downloading from the OpenAIR website
3. A fallback mode using the already-downloaded or provided IR files

Usage:
  python download_real_irs.py sampledata/real_irs

Manual download steps:
  1. Browse https://www.openair.hosted.york.ac.uk/?page_id=36
  2. Click on each IR name to open its page
  3. Find the WAV download link (usually in the post content)
  4. Save to sampledata/real_irs/
"""

import os
import sys
import wave
from pathlib import Path

# Recommended IRs for benchmarking (50 total, organized by category)
RECOMMENDED_IRS = {
    "Hall (5)": [
        "Central Hall, University of York",
        "Arthur Sykes Rymer Auditorium",
        "1st Baptist Church Nashville",
        "Elveden Hall",
        "Creswell Crags",
    ],
    "Church (5)": [
        "Heslington Church",
        "St. Paul's Cathedral",
        "York Minster",
        "Lady Chapel, St Albans Cathedral",
        "St. Andrew's Church",
    ],
    "Chamber (5)": [
        "Alcuin College, University of York",
        "Clifford's Tower, York",
        "D/L/028 Hendrix Hall Derwent",
        "The Dixon Studio Theatre",
        "York Guildhall Council Chamber",
    ],
    "Room (5)": [
        "P/L/001 Physics, University of York",
        "Jack Lyons Concert Hall",
        "Ron Cooke Hub, University of York",
        "Sports Centre, University of York",
        "Spring Lane Building, University of York",
    ],
    "Outdoor (5)": [
        "Abies Grandis Forest, Wheldrake Wood",
        "Koli National Park - Summer",
        "Koli National Park - Winter",
        "Troller's Gill",
        "Forest Scale Model",
    ],
    "Synthetic (25)": [
        "dirac_k2.wav, dirac_k4.wav, ..., dirac_k32.wav (5 files)",
        "minphase_*.wav (5 files)",
        "linphase_*.wav (5 files)",
        "mixedphase_*.wav (5 files)",
        "reverb_plate.wav, reverb_spring.wav (2 files)",
    ],
}

def check_existing_irs(output_dir):
    """Check which IRs already exist in the output directory."""
    if not output_dir.exists():
        return []
    return list(output_dir.glob("*.wav"))

def main():
    output_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("sampledata/real_irs")
    output_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 70)
    print("  Real IR Download Helper")
    print("=" * 70)
    print()
    print(f"  OpenAIR does not provide direct WAV download URLs.")
    print(f"  Manual download from the OpenAIR website is required.")
    print(f"  See: https://www.openair.hosted.york.ac.uk/?page_id=36")
    print()
    print(f"  Recommended IRs for benchmarking (50 total):")
    print()

    for category, irs in RECOMMENDED_IRS.items():
        print(f"  [{category}]")
        for ir in irs:
            print(f"    - {ir}")
        print()

    print(f"  Output directory: {output_dir.resolve()}")

    # Check for existing files
    existing = check_existing_irs(output_dir)
    if existing:
        print(f"\n  Already present: {len(existing)} files")
        for f in existing:
            try:
                with wave.open(str(f), 'r') as w:
                    dur = w.getnframes() / w.getframerate()
                    print(f"    {f.name}: {w.getnframes()}samples, {dur:.1f}s, {w.getnchannels()}ch")
            except:
                print(f"    {f.name}: (unreadable)")
    else:
        print(f"\n  No IR files found yet. Download manually from OpenAIR.")
        print()
        print(f"  Alternatively, synthetic IRs are available in:")
        print(f"    sampledata/synthetic/ (22 files)")

    print(f"\n{'=' * 70}")
    print(f"  Synthetic IRs generated by tools/generate_synthetic_irs.py")
    print(f"{'=' * 70}")
    main()
