<#
.SYNOPSIS
    Fix C# Dev Kit IComponentExportsService error for C++ projects.

.DESCRIPTION
    When VS Code with C# Dev Kit (ms-dotnettools.csdevkit) opens a C++ project
    that happens to have .csproj or .sln files (e.g., in tools/ subdirectory),
    C# Dev Kit tries to load them and fails with:

        Failed: Query for all projects with error: Error: Exception while talking to proxy:
        Error: Microsoft.VisualStudio.ProjectSystem.Server.IComponentExportsService サービスのインスタンスが見つかりません。

    This script:
    1. Removes the stale ConvoPeq.sln generated by C# Dev Kit in workspace storage
    2. Cleans the .vs/ConvoPeq.slnx solution cache
    3. Reports status

    The proper fix is configuring .vscode/settings.json to prevent C# Dev Kit
    from activating on C++ projects (handled separately in settings.json).

.PARAMETER DryRun
    Check only, do not remove files.

.EXAMPLE
    pwsh -File fix-csdevkit-cpp-project-conflict.ps1
#>

param(
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

$workspaceStorage = "$env:USERPROFILE\AppData\Roaming\Code\User\workspaceStorage"
# Find workspace hash for ConvoPeq
$workspaceHash = Get-ChildItem $workspaceStorage -Directory | Where-Object {
    Test-Path "$($_.FullName)\ms-dotnettools.csdevkit"
} | Select-Object -First 1

if (-not $workspaceHash) {
    Write-Host "[INFO] No C# Dev Kit workspace storage found for this project." -ForegroundColor Cyan
    exit 0
}

$csdevkitStorage = "$($workspaceHash.FullName)\ms-dotnettools.csdevkit"
Write-Host "[INFO] C# Dev Kit workspace storage: $csdevkitStorage" -ForegroundColor Cyan

# Check for stale .sln file
$slnFile = Join-Path $csdevkitStorage "ConvoPeq.sln"
if (Test-Path $slnFile) {
    Write-Host "[WARN] Stale solution file found: $slnFile" -ForegroundColor Yellow
    if (-not $DryRun) {
        Remove-Item $slnFile -Force
        Write-Host "[OK] Removed stale solution file." -ForegroundColor Green
    } else {
        Write-Host "[DRY-RUN] Would remove: $slnFile" -ForegroundColor Yellow
    }
} else {
    Write-Host "[OK] No stale solution file found." -ForegroundColor Green
}

# Check for testStore directory
$testStore = Join-Path $csdevkitStorage "testStore"
if (Test-Path $testStore) {
    Write-Host "[INFO] testStore directory exists." -ForegroundColor Cyan
}

Write-Host ""
Write-Host "NOTE: The primary fix is in .vscode/settings.json:" -ForegroundColor Cyan
Write-Host "  - 'dotnet.server.useOmnisharp': false" -ForegroundColor Gray
Write-Host "  - 'csharp.excludeFromProjectLoad': excludes .csproj/.sln files" -ForegroundColor Gray
Write-Host "  - 'msbuildProjectTools.addon.disabled': true" -ForegroundColor Gray
Write-Host ""
Write-Host "After applying settings, restart VS Code." -ForegroundColor Yellow
